apiVersion: v1
kind: Service
metadata:
  name: threat-api-svc
  labels:
    app: threat-api
    tier: backend
spec:
  selector:
    labels:
      app: threat-api
      tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      NodePort: 30080
